# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - "5.3"

# WordPress version used in first build configuration.
env:
    - WP_VERSION=3.9.1 WP_TESTS_DIR=/tmp/wordpress/tests/phpunit

# Only test the unittests branch for now
branches:
    only:
        - unittests

# Clones WordPress and configures our testing environment.
before_script:
    - export SLUG=$(basename $(pwd))
    - git clone https://github.com/tierra/wordpress.git /tmp/wordpress
    - cd ..
    - mv $SLUG "/tmp/wordpress/src/wp-content/themes/$SLUG"
    - cd /tmp/wordpress
    - git checkout $WP_VERSION
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    - cd "/tmp/wordpress/src/wp-content/themes/$SLUG"

script: phpunit
